### ISSUE TITLE
script for training reid network

### ISSUE THREAD

**Issue by ly59782** [dvl-tum/mot_neural_solver#21]
we find your research  wonderful !!  however, we want to further improve the perfomance of the reid network, can you provide us with the script for training reid network? many thanks!

**Comment by gbraso** [comment]
Hi! Sorry for my late reply! Unfortunately, that's not too easy, because I used an older version of torchreid, and I used the dataset DukeMTMC, which is no longer available. Hence, I'd suggest you work directly with [torchreid](https://github.com/KaiyangZhou/deep-person-reid), which is great. I might consider adding support for training reid models from this repo in the future, but not at the moment!
